name: First
on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello!
        run: |
          echo "Hello, world!"
          echo "${{ github.event.pull_request }}"

      - name: Repository Dispatch
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "pull_request": { "title": "${{ github.event.pull_request.title }}", "body": "${{ github.event.pull_request.body }}", "number": "${{ github.event.pull_request.number }}", "head": "${{ github.event.pull_request.head.ref }}", "base": "${{ github.event.pull_request.base.ref}}"}}'
