name: Second
on:
  workflow_run:
    workflows:
      - "First"
    types:
      - "completed"
    branches:
      - main
      - develop
  repository_dispatch:
    types:
      - release-event

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print out event_name
        run: |
          echo "${{ github.event_name }}"

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' }}
    needs: test
    steps:
      - name: check pull_request title
        uses: kaisugi/action-regex-match@v1.0.0
        id: regex-match
        with:
          text: ${{ github.event.client_payload.pull_request.title }}
          regex: "^(\\d+\\.\\d+\\.\\d+)$"

      - name: create asset files
        if: ${{ steps.regex-match.outputs.match != ''}}
        run: |
          mkdir -p /tmp/assets
          echo "create files" > test.txt
          tar zcvf /tmp/assets/test1.tar.gz test.txt
          tar zcvf /tmp/assets/test2.tar.gz test.txt

      - name: release
        if: ${{ steps.regex-match.outputs.match != ''}}
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/assets/*.tar.gz
          name: ${{ github.event.client_payload.pull_request.title }}
          tag_name: ${{ github.event.client_payload.pull_request.title }}
          body: fromJSON(${{ github.event.client_payload.pull_request.body }})
          draft: true
          prerelease: false
          generate_release_notes: true
