name: Second
on:
  workflow_run:
    workflows:
      - "First"
    types:
      - "completed"
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: retrive github script context
        uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))

      - name: checkout
        # if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions/checkout@v4

      - name: printout
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.event.workflow_run.event }}""
          echo "${{ github.ref_name }}""

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' && github.event.workflow_run.event == 'pull_request' }}
    needs: test
    steps:
      - name: check pull_request title
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.workflow_run.head_commit.message }}
          regex: "^(\\d+\\.\\d+\\.\\d+)$"

      - name: Hello!
        run: |
          echo "${{ github.event.workflow_run.event }}""

      - name: omg
        uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload.pull_request))
            core.info(JSON.stringify(context.payload.workflow_run))
            core.info(JSON.stringify(context.payload.workflow_run.event))
