name: Second
on:
  workflow_run:
    workflows:
      - "First"
    types:
      - "completed"
    branches:
      - main
      - develop
  repository_dispatch:
    types: [release-event]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print out event_name
        run: |
          echo "${{ github.event_name }}"

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' }}
    needs: test
    steps:
      - name: check pull_request title
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.repository_dispatch.client_payload.pull_request.title }}
          regex: "^(\\d+\\.\\d+\\.\\d+)$"

      - name: omg
        uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload.pull_request))
            core.info(JSON.stringify(context.payload.workflow_run))
            core.info(JSON.stringify(context.payload.workflow_run.event))
